---
- name: Run Wazuh Agent Installation Script
  hosts: all
  become: yes

  tasks:
    - name: Download the Wazuh agent installation script from GitHub
      get_url:
        url: https://raw.githubusercontent.com/Thantzawsoe/ansible/576f03cfc92150f2f43382db36b4839e61314e69/install_wazuh_agent.sh
        dest: /tmp/install_wazuh_agent.sh
        mode: '0755'

    - name: Ensure the Wazuh agent installation script is executable
      file:
        path: /tmp/install_wazuh_agent.sh
        mode: '0755'
        state: file

    - name: Run the Wazuh agent installation script
      command: /tmp/install_wazuh_agent.sh
      environment:
        WAZUH_MANAGER: '192.168.30.194'
