---
- name: Install and configure Wazuh Agent
  hosts: all
  become: yes

  tasks:
    - name: Download the Wazuh agent package
      get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.8.0-1_amd64.deb
        dest: /tmp/wazuh-agent_4.8.0-1_amd64.deb

    - name: Install the Wazuh agent package
      command: >
        dpkg -i /tmp/wazuh-agent_4.8.0-1_amd64.deb
      environment:
        WAZUH_MANAGER: '192.168.30.193'
        WAZUH_AGENT_GROUP: 'default'

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes

    - name: Enable the Wazuh agent service
      systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start the Wazuh agent service
      systemd:
        name: wazuh-agent
        state: started

    - name: Clean up the Wazuh agent package
      file:
        path: /tmp/wazuh-agent_4.8.0-1_amd64.deb
        state: absent
