---
- name: Run Wazuh Agent Installation Script
  hosts: all
  become: yes

  tasks:
    - name: Download the Wazuh agent installation script from GitHub
      get_url:
        url: https://raw.githubusercontent.com/your_github_username/your_repository_name/main/install_wazuh_agent.sh
        dest: /tmp/install_wazuh_agent.sh
        mode: '0755'

    - name: Run the Wazuh agent installation script
      command: /tmp/install_wazuh_agent.sh
